# Generated by Django 3.0.6 on 2020-06-03 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200603_0447'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
