# Generated by Django 3.0.6 on 2020-06-03 05:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=30, null=True, verbose_name='SKU')),
                ('title', models.CharField(blank=True, max_length=80, null=True, verbose_name='Title')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('category_num', models.IntegerField(default=-1, verbose_name='Category Number')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('seller', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
