# Generated by Django 3.0.6 on 2020-06-05 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category_num',
            field=models.IntegerField(choices=[(-1, 'Unassigned'), (2, 'Home'), (3, 'Outdoor')], default=-1, verbose_name='Category Number'),
        ),
    ]
