# Generated by Django 3.0.6 on 2020-06-09 06:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0006_listing_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category_num',
            field=models.IntegerField(choices=[(-1, 'Unassigned'), (2, 'Apple iPhone 11'), (3, 'Samsung Galaxy S20')], default=-1, verbose_name='Category Number'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Listing')),
            ],
            options={
                'ordering': ['created_on'],
            },
        ),
    ]
