# Generated by Django 3.0.6 on 2020-06-12 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_auto_20200609_0632'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
