# Generated by Django 3.0.6 on 2020-06-14 00:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_auto_20200612_0714'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='attachments')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Listing')),
            ],
        ),
    ]
