# Generated by Django 3.0.6 on 2020-06-14 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_attachment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Attachment',
        ),
    ]
