# Generated by Django 3.0.6 on 2020-06-14 04:45

from django.db import migrations, models
import django.db.models.deletion
import store.models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_delete_attachment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.FileField(blank=True, null=True, upload_to=store.models.Gallery.img_directory_path)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Listing')),
            ],
        ),
    ]
