# Generated by Django 3.0.6 on 2020-06-14 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_gallery'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gallery',
            old_name='images',
            new_name='image',
        ),
    ]
