# Generated by Django 3.0.6 on 2020-06-14 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_auto_20200614_0639'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='images',
        ),
    ]
