# Generated by Django 3.0.6 on 2020-06-17 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_transaction_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='buyer',
        ),
    ]
