# Generated by Django 3.0.6 on 2020-06-20 05:55

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_category_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.Category'),
        ),
    ]
