# Generated by Django 3.0.6 on 2020-06-28 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0022_category_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category_num',
        ),
    ]
