# Generated by Django 3.0.6 on 2020-08-02 03:33

from django.db import migrations, models
import uuid


def create_uuid(apps, schema_editor):
    MyModel = apps.get_model('store', 'Listing')
    for row in MyModel.objects.all():
        row.listing_id = uuid.uuid4()
        row.save()


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0027_auto_20200714_0519'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='listing_id',
            field=models.CharField(default=uuid.uuid4, max_length=8),
        ),
        migrations.RunPython(create_uuid),
        migrations.AlterField(
            model_name='listing',
            name='listing_id',
            field=models.UUIDField(default=uuid.uuid4, unique=True, max_length=8)
        )
    ]
