# Generated by Django 3.0.6 on 2020-08-02 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0029_remove_listing_listing_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='listing_code',
            field=models.CharField(default='IA275M4A', max_length=8),
        ),
    ]
