# Generated by Django 3.0.6 on 2020-08-02 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0030_listing_listing_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='listing_code',
            field=models.CharField(max_length=8, null=True),
        ),
    ]
